##########################################################
# BP INFO
#
#	*.* 127.0.0.1

##############################################################


plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
plugin = eosio::http_client_plugin
plugin = eosio::net_plugin
plugin = eosio::producer_plugin
#plugin = eosio::producer_api_plugin
plugin = eosio::state_history_plugin
plugin = eosio::trace_api_plugin
#plugin = eosio::history_plugin
#plugin = eosio::history_api_plugin

trace-dir = "traces"
blocks-dir = "blocks"
snapshots-dir = "snapshots"
state-history-dir = "state-history"

agent-name = "GF LEAP EVM TESTNET"
state-history-endpoint = 0.0.0.0:17777
http-server-address = 0.0.0.0:18880
p2p-listen-endpoint = ****:9876
p2p-server-address = ****:9876

p2p-peer-address = ****:9876 #BP 1
p2p-peer-address = ****:9876 #BP 2

chain-threads = 12
http-threads = 16
net-threads = 16
producer-threads = 6
enable-stale-production = false

#--disable-replay-opts
#--delete-state-history ---> clear state history files
trace-history = true
chain-state-history = true 
trace-history-debug-mode = true

# State-history config
state-history-retained-dir = "state-history/retained"
state-history-archive-dir = "state-history/archive"
state-history-stride = 1000000 #start new file after fill state
#state-history-log-retain-blocks = 10000000 #cut size of state
max-retained-history-files = 20000

contracts-console = true
read-mode = speculative
validation-mode = full
database-map-mode = heap #mapped

#filter-on = *
trace-no-abis = true
access-control-allow-origin = *
max-body-size = 2097152
http-max-bytes-in-flight-mb = 1024
http-max-response-time-ms = 120
verbose-http-errors = true
http-validate-host = false
p2p-max-nodes-per-host = 24
p2p-accept-transactions = true
allowed-connection = any
#  --peer-key arg                        Optional public key of peer allowed to
#                                        connect.  May be used multiple times.
#  --peer-private-key arg                Tuple of [PublicKey, WIF private key]
#                                        (may specify multiple times)
max-clients = 150
connection-cleanup-period = 30 
max-cleanup-time-msec = 10
sync-fetch-span = 100
use-socket-read-watermark = 0 #Enable experimental socket read watermark optimization
peer-log-format = ["${_name}" - ${_cid} ${_ip}:${_port} ${_lip}:${_lport}]

wasm-runtime = eos-vm-jit
abi-serializer-max-time-ms = 2000
chain-state-db-size-mb = 8192
chain-state-db-guard-size-mb = 128
signature-cpu-billable-pct = 50
eos-vm-oc-cache-size-mb = 2048
eos-vm-oc-compile-threads = 16
eos-vm-oc-enable = 1

incoming-transaction-queue-size-mb = 2048
max-transaction-time = 360
max-irreversible-block-age = -1
max-block-cpu-usage-threshold-us = 5000
max-block-net-usage-threshold-bytes = 1024

keosd-provider-timeout = 15
